apiVersion: batch/v1
kind: Job
metadata:
  name: job${jobName}
spec:
  template:
    spec:
      restartPolicy: Never
      nodeSelector:
        nodetype: worker
        ${labelKey}: ${labelValue}
      containers:
      - name: test
        image: ${imageName}
        env:
          - name: HF_VAR_ENABLE_NETHOGS
            value: "1"
          - name: HF_VAR_WORK_DIR
            value: "/tmp/work_dir"
          - name: HF_VAR_WAIT_FOR_INPUT_FILES
            value: "0"
          - name: HF_VAR_NUM_RETRIES
            value: "1"
        command:
          - "/bin/sh"
          - "-c"
          - >
            cp -R /work_dir /tmp;
            ${command};
            exitCode=$?;
            if [ $exitCode -ne 0 ]; then echo "Command ${command} returned exit code. $exitCode. Job fails." ; exit 1 ; else cp /tmp/work_dir/logs-hf/* /work_dir/logs-hf/ ; fi ;
        workingDir: ${volumePath}
        resources:
          requests:
            cpu: ${cpuRequest}
            memory: ${memRequest}
        volumeMounts:
        - name: my-pvc-nfs
          mountPath: ${volumePath}
      volumes:
      - name: workflow-data
        emptyDir: {}
      - name: my-pvc-nfs
        persistentVolumeClaim:
          claimName: nfs
